### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [jacksnt/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jacksnt** [comment]
Hi Billy, 

Addressed. Added the following to the "<meta name="viewport" content="width=device-width, initial-scale=1.0">" within the application.html.erb file.

Best,
Jack

**Comment by jacksnt** [comment]
Hi Billy,

Addressed the issue you mentioned. Added the updated tag in the head of the application.html.erb file.

Best,
Jack

**Comment by BillyMassey** [comment]
Well done, Jack!

Keep up the great work coding
